In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import control
import copy

In [2]:
# define time vector
ts = 1e-4
t_end = 0.1
steps = int(1/ts)
t = np.arange(0, t_end+ts, ts)
num_samples = len(t)

# define values of the parameter
R = 0.4
L = 2.3e-3
C = 10e-6
LT = 2.3e-3
R_load = 14

vi1 = 230
vi2 = 230

In [3]:
u = np.array([vi1, vi2])[:,None] * np.ones((2,len(t)))

## 2 Nodes with 2 connections

In [ ]:
#def varaibles

R1 = R
L1 = L
C1 = C
R2 = R
L2 = L
C2 = C
LT1 = LT
LT2 = LT
RT1 = R
RT2 = R

In [ ]:
i10 = 0
v10 = 0
iT10 = 0
i20 = 0
v20 = 0
iT20 = 0
t0 = 0

# x0 = np.array([i10, v10, iT10, i20, v20, iT20])
x0 = [i10, v10, iT10, i20, v20, iT20]

In [ ]:
A_source1 = np.array([[-R1/L1, -1/L1],
                     [1/C, 0]])

A_source2 = np.array([[-R2/L2, -1/L2],
                     [1/C, 0]])

A_zeros = np.zeros((2,2))

A_source = np.block([[A_source1, A_zeros],
                     [A_zeros, A_source2]])

In [ ]:
A_col1 = np.array([[0,0],
                   [-1/C1, 0]])

A_col2 = np.array([[0,0],
                   [0, -1/C2]])

A_col = np.block([[A_col1],
                 [A_col1]])

In [ ]:
A_row1 = np.array([[0, 1/LT1],
                  [0, 0]])

A_row2 = np.array([[0, 0],
                  [0, 1/LT2]])

A_row = np.block([A_row1, A_row2])

In [ ]:
A_transitions = np.array([[-(RT1+R_load)/LT1, -R_load/LT1],
                          [-R_load/LT1, -(RT2+R_load)/LT2]])

In [ ]:
A = np.block([[A_source, A_col],
              [A_row, A_transitions]])

In [ ]:
B_source1 = np.array([[1/L1, 0],
                     [0, 0]])
B_source2 = np.array([[0, 1/L2],
                     [0, 0]])

B_transition = np.zeros((2,2))

B = np.block([[B_source1],
              [B_source2],
              [B_transition]])

In [ ]:
C = np.ones((1,6))

In [ ]:
D = 0

In [ ]:
sys = control.ss(A, B, C, D)

In [ ]:
T, yout, xout = control.forced_response(sys, T=t, U=u, X0=x0, return_x=True, squeeze=True)

In [ ]:
xout.shape

In [ ]:
plt.plot(t, xout[1], label='v1')
# plt.plot(t,result[:steps,0], label = 'i1')
plt.xlabel(r'$t\,/\,\mathrm{s}$')
plt.ylabel('$v_{\mathrm{1}}\,/\,\mathrm{V}$')
# plt.title('{}'.format())
plt.legend()
plt.grid()
plt.show()

## 2 Nodes with 3 connections

In [ ]:
#def varaibles

R1 = R
L1 = L
C1 = C
R2 = R
L2 = L
C2 = C
LT12 = LT
LT23 = LT
LT13 = LT
RT12 = R # For checking result set this on to inf
RT23 = R
RT13 = R

In [ ]:
i10 = 0
v10 = 0
i20 = 0
v20 = 0
iT120 = 0
iT230 = 0
iT130 = 0
t0 = 0

# x0 = np.array([i10, v10, iT10, i20, v20, iT20])
x0 = [i10, v10, i20, v20, iT120, iT230, iT130]

In [ ]:
A_source1 = np.array([[-R1/L1, -1/L1],
                     [1/C, 0]])
A_source2 = np.array([[-R2/L2, -1/L2],
                     [1/C, 0]])

A_zeros = np.zeros((2,2))

A_source = np.block([[A_source1, A_zeros],
                     [A_zeros, A_source2]])

In [ ]:
A_col1 = np.array([[0,0,0],
                   [-1/C1, -1/C1, 0]])
A_col2 = np.array([[0,0,0],
                   [1/C2, 0, -1/C2]])
A_col = np.block([[A_col1],
                 [A_col1]])

A_row1 = np.array([[0, 1/LT12],
                  [0, 1/LT13],
                  [0, 0]])

A_row2 = np.array([[0, 1/LT12],
                  [0, 0],
                  [0, 1/LT23]])

A_row = np.block([A_row1, A_row2])

In [ ]:
A_transitions = np.array([[-RT12/LT12, 0, 0],
                          [0, -(RT13+R_load)/LT13, -R_load/LT13],
                          [0, -R_load/LT23, -(RT23+R_load)/LT23]])

In [ ]:
A = np.block([[A_source, A_col],
              [A_row, A_transitions]])

In [ ]:
B_source1 = np.array([[1/L1, 0],
                     [0, 0]])
B_source2 = np.array([[0, 1/L2],
                     [0, 0]])

B_transition = np.zeros((3,2))

B = np.block([[B_source1],
              [B_source2],
              [B_transition]])

In [ ]:
C = np.ones((1,7))

In [ ]:
D = 0

In [ ]:
sys = control.ss(A, B, C, D)

In [ ]:
T, yout, xout = control.forced_response(sys, T=t, U=u, X0=x0, return_x=True, squeeze=True)

In [ ]:
plt.plot(t, xout[1], label='v1')
# plt.plot(t,result[:steps,0], label = 'i1')
plt.xlabel(r'$t\,/\,\mathrm{s}$')
plt.ylabel('$v_{\mathrm{1}}\,/\,\mathrm{V}$')
# plt.title('{}'.format())
plt.legend()
plt.grid()
plt.show()

# Playground

In [6]:
num_source = 2 # num of sources
num_loads = 1 # num of loads

ele_tot = num_source + num_loads # total elements

num_lines = ele_tot**2 - ele_tot # upper limit

In [158]:
class NodeConstructor:
    def __init__(self, num_source, num_loads, S2S_p=0.1, S2L_p=0.8):
        self.num_source = num_source
        self.num_loads = num_loads
        self.tot_ele = num_source + num_loads
        self.S2S_p = S2S_p
        self.S2L_p = S2L_p
        self.cntr = 0
        self.num_connections = 3
    
    def to2be_or_n2b(self, x, p):
        
        # To count up the connection, cntr is returned.
        # If only one type of cabel is used this is not necessary an can be replaced by 1
        
        if x < p:
            self.cntr += 1  
            return self.cntr
        else:
            x = 0
            return x
    
    def generate_CM(self):
        '''
        Constructs the CM
        '''
        
        self.cntr = 0

        # Get a upper triangular matrix
        mask = np.tri(self.tot_ele).T
        CM = np.random.rand(self.tot_ele,self.tot_ele) * mask # fill matrix with random entries between [0,1]
        CM = CM - np.eye(CM.shape[0]) * np.diag(CM) # delet diagonal bc no connection with itself

        # Go throught the matrix
        # -1 bc last entrie is 0 anyway
        # start at i, bc we need to check only upper triangle

        for i in range(self.tot_ele-1): 
            for j in range(i, self.tot_ele-1): 
                if j >= self.num_source: # select propability according to column
                    CM[i, j+1] = self.to2be_or_n2b(CM[i, j+1], self.S2L_p) 
                else:
                    CM[i, j+1] = self.to2be_or_n2b(CM[i, j+1], self.S2S_p)

        CM = CM - CM.T # copy with negative sign to lower triangle
        
        self.num_connections = self.cntr

        return CM
    
    def get_A_source(self, R, C, L):
        # this matrix is always a 2x2 for inverter
        A = np.zeros((2,2))
        A[0,0] = -R/L
        A[0,1] = -1/L
        A[1,0] =  1/C
        return A_source
    
    def get_A_col(self, source_x, C, CM):
        # this matrix is (2 x num_connections)
        # for this case C is assumed to be just an int.
        # Later C could be an array with the diffrent paramters and would be indexed via C[source_x] 
        
        A_col = np.zeros((2, self.num_connections))
        
        CM_row = CM[source_x-1]
        
        indizes = list(CM_row[CM_row != 0]) # get entries unequal 0
        signs = np.sign(indizes) # get signs
        indizes_ = indizes*signs # delet signs from indices
        
        for i, (idx, sign) in enumerate(zip(indizes_, signs)):
            A_col[1,idx-1] = sign * -C
                                        
        return A_col
    
    def get_A_row(self, source_x, LT, CM):
        
        print(CM)
        
        A_row = np.zeros((2, self.num_connections))
        
        CM_col = CM[source_x-1]
        
        indizes = list(CM_col[CM_col != 0]) # get entries unequal 0
        signs = np.sign(indizes) # get signs
        indizes_ = indizes*signs # delet signs from indices
        
        for i, (idx, sign) in enumerate(zip(indizes_, signs)):
            A_row[1,idx-1] = sign * - LT
        
        return A_row.T
    
    def get_A_transition():
        pass
    
    def generate_A():
        pass
    
    def generate_B():
        pass
    
    def generate_C():
        return np.ones(1, self.tot_ele)
    
    def generate_D():
        return 0

In [159]:
Node_3S_2L = NodeConstructor(2, 1)

In [96]:
CM = Node_3S_2L.generate_CM()

In [160]:
CM = np.array([[0,1,2],
              [-1, 0, 3],
              [-2, -3, 0]])

In [161]:
Node_3S_2L.get_A_col(2, 10, CM)

(1, -1)
0
(3, 1)
2


array([[  0.,   0.,   0.],
       [ 10.,   0., -10.]])

In [163]:
Node_3S_2L.get_A_row(2, 10, CM)

[[ 0  1  2]
 [-1  0  3]
 [-2 -3  0]]
[-1  0  3]
[-1, 3]
(1, -1)
(3, 1)


array([[  0.,  10.],
       [  0.,   0.],
       [  0., -10.]])

In [ ]:
con_m = np.array([[0, 1, 2],
                  [-1, 0, 3],
                  [-2, -3, 0]], dtype=np.int32)

In [ ]:
def generate_source(R, C, L):
    A = np.zeros((2,2))
    A[0,0] = -R/L
    A[0,1] = -1/L
    A[1,0] =  1/C
    return A